### ISSUE TITLE
Support React v16.3 context API

### ISSUE THREAD

**Issue by jaydenseric** [ctrlplusb/react-tree-walker#22] opened 2018-02-28 08:45 UTC
[Function as children components](https://reactpatterns.com/#function-as-children) are becoming very popular. In React v16.3 the new context API uses this pattern.

How do you walk into the children functions, so you can keep recursing the tree and visit deeper components?

For context, I am attempting to SSR [`Query` components in `graphql-react`](https://github.com/jaydenseric/graphql-react#query).

**Comment by jaydenseric** [comment] 2018-03-02 02:48
Ok, so it turns out my issue is not with function as children components.

With a simple test eventually `foobar` logs as the deepest node, as expected:

```jsx
const TestComponent = ({ children }) => children('foobar')
const tree = <TestComponent>{message => <p>{message}</p>}</TestComponent>

reactTreeWalker(
  tree,
  element => {
    console.log(element)
    return true
  }
)
```

What does not work is `Consumer` from the new React context API:

```jsx
const { Provider, Consumer } = React.createContext()
const tree = (
  <Provider value={{ message: 'foobar' }}>
    <Consumer>{({ message }) => <p>{message}</p>}</Consumer>
  </Provider>
)

reactTreeWalker(
  tree,
  element => {
    console.log(element)
    return true
  }
)
```

The deepest node is logged as `[Function]`. Basically, [the logic](https://github.com/ctrlplusb/react-tree-walker/blob/2.1.3/src/index.js#L188) incorrectly thinks `Consumer` is a basic string or dom node element.

**Comment by ctrlplusb** [comment] 2018-03-14 15:18
Looks like this is ready to be worked on 😀

https://github.com/apollographql/react-apollo/pull/1742/files#diff-f8938b597e7a7647b9ea5589d55d3a26

@jaydenseric are you happy with running with this?

**Comment by jaydenseric** [comment] 2018-03-14 23:34
@ctrlplusb thanks, but I've already worked it out in `graphql-react`: https://github.com/jaydenseric/graphql-react/blob/master/src/preload.mjs#L96

**Comment by oyeanuj** [comment] 2018-03-30 15:54
@ctrlplusb Can I come back to the original question at the start of the thread by @jaydenseric: 
> How do you walk into the children functions, so you can keep recursing the tree and visit deeper components?

What is the expected behavior here?

**Comment by jaydenseric** [comment] 2018-04-04 02:42
@ctrlplusb relevent discussion: https://github.com/facebook/react/pull/12501#issuecomment-378449839

**Comment by lemonmade** [comment] 2018-06-02 22:43
Has anyone taken this up? Would really like to convert a project using tree-walker to use new React context.

**Comment by dan-lee** [comment] 2018-06-10 20:15
@ctrlplusb I tried something, maybe the PR can serve as a starting point?

**Comment by ctrlplusb** [comment] 2018-06-19 14:35
Just merged @dan-lee's and published work on this. 🎉

**Closed by ctrlplusb** 2018-06-19 14:35 UTC
Labels: enhancement
